### ISSUE TITLE
InetAddress.java line 434

### ISSUE THREAD

**Issue by charlesmaderefabric** [charlesmadere/smash-ranks-android#48]
#### in java.net.InetAddress.lookupHostByName

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/charles-maderes-projects/android/apps/com.garpr.android/issues/5b1453c36007d59fcdcdbe03?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/charles-maderes-projects/android/apps/com.garpr.android/issues/5b1453c36007d59fcdcdbe03?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by charlesmadere** [comment]
this is an extremely old version of the app
